ALTER TABLE roles ADD COLUMN IF NOT EXISTS description VARCHAR(255);
ALTER TABLE roles ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE roles DROP CONSTRAINT IF EXISTS roles_name_check;

UPDATE roles
SET active = TRUE
WHERE active IS NULL;

CREATE TABLE IF NOT EXISTS role_features (
    role_id BIGINT NOT NULL,
    feature_name VARCHAR(60) NOT NULL,
    CONSTRAINT fk_role_features_role
        FOREIGN KEY (role_id) REFERENCES roles(id)
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name VARCHAR(80);
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name VARCHAR(80);
ALTER TABLE users ADD COLUMN IF NOT EXISTS flat VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS building VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS area VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(80);
ALTER TABLE users ADD COLUMN IF NOT EXISTS state VARCHAR(80);
ALTER TABLE users ADD COLUMN IF NOT EXISTS country VARCHAR(80);
ALTER TABLE users ADD COLUMN IF NOT EXISTS pincode VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image BYTEA;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image_content_type VARCHAR(100);

ALTER TABLE tickets ADD COLUMN IF NOT EXISTS address VARCHAR(500);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS service_type VARCHAR(30);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS location_link VARCHAR(1000);
